### ISSUE TITLE
Add section on security testing

### ISSUE THREAD

**Issue by ericalofstrom** [Omegapoint/tdd2-java#10]
We should add a section where we talk about security testing

**Comment by altenstedt** [comment]
Maybe we should consider to introduce a full IdP so that we can do a lab on security testing?

We should then consider the complexity that this adds: is it worth it?

**Comment by altenstedt** [comment]
We are trying out just adding a slide and perhaps a demo on 2019-04-09.  Revisit this afterwards.

**Comment by altenstedt** [comment]
We reason that having an IdP is too complex.  But showing real code from a real project is very powerful, so try to do that.
