### ISSUE TITLE
Move introductory email to repository

### ISSUE THREAD

**Issue by altenstedt** [Omegapoint/tdd2-java#7]
The students could have come much better prepared if the invitation had contained better instructions:

* At least build the master branch at home (pull all dependencies)
* Run all the tests and see that L0 pass and L1-3 does not
* Follow the instructions and connect to a MongoDB, and run L1-3

The introductory email is currently in Erica's inbox.  Move it to a file EMAIL.md or similar and check it in.

**Comment by ericalofstrom** [comment]
Added EMAIL.md to root of repo
